name: Test

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Yarn
              uses: mskelton/setup-yarn@v1.2.1

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install and Test 🔧
              run: |
                  yarn install
                  yarn run test
